# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Anthony/Documents/ECE530/project_2/project_2.cache/wt [current_project]
set_property parent.project_path C:/Users/Anthony/Documents/ECE530/project_2/project_2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/Anthony/Documents/ECE530/project_2/project_2.srcs/sources_1/new/seven_seg.vhd
  C:/Users/Anthony/Documents/ECE530/project_2/project_2.srcs/sources_1/new/decoder.vhd
  C:/Users/Anthony/Documents/ECE530/project_2/project_2.srcs/sources_1/new/top_level.vhd
}
read_xdc C:/Users/Anthony/Documents/ECE530/project_2/project_2.srcs/constrs_1/new/decoder.xdc
set_property used_in_implementation false [get_files C:/Users/Anthony/Documents/ECE530/project_2/project_2.srcs/constrs_1/new/decoder.xdc]

synth_design -top top_level -part xc7a100tcsg324-1
write_checkpoint -noxdef top_level.dcp
catch { report_utilization -file top_level_utilization_synth.rpt -pb top_level_utilization_synth.pb }
